sudo: required
dist: trusty
language: generic

install:
  # Travis CI does not make the home directory world readable by default,
  # which prevents Apache from reading the server source.
  - sudo chmod 755 /home/travis/
  - ./setup/setup.sh

script:
  - ./test.sh
